import type { PantryItem } from "@/components/dashboard/kitchen/types";

export const MOCK_PANTRY_ITEMS: PantryItem[] = [
  {
    id: "1",
    name: "Semi-skimmed Milk",
    type: "ingredient",
    location: "Fridge",
    countAsUnits: false,
    batches: [
      { id: 1, qty: 1, fillLevel: "half", sealed: false, bestBefore: "2026-04-01" },
      { id: 2, qty: 1, fillLevel: "sealed", sealed: true, bestBefore: "2026-04-08" },
    ],
  },
  {
    id: "2",
    name: "Eggs",
    type: "ingredient",
    location: "Fridge",
    countAsUnits: true,
    batches: [{ id: 3, qty: 8, fillLevel: "sealed", sealed: true, bestBefore: "2026-04-05" }],
  },
  {
    id: "3",
    name: "Chicken Breast",
    type: "ingredient",
    location: "Freezer",
    countAsUnits: false,
    batches: [{ id: 4, qty: 1, fillLevel: "sealed", sealed: true, bestBefore: "2026-06-15" }],
  },
  {
    id: "4",
    name: "Jollof Rice",
    type: "cooked_meal",
    location: "Fridge",
    countAsUnits: false,
    batches: [
      {
        id: 5,
        qty: 1,
        fillLevel: "half",
        sealed: false,
        bestBefore: "2026-03-30",
        dateMade: "2026-03-26",
      },
    ],
  },
  {
    id: "5",
    name: "Cheddar Cheese",
    type: "ingredient",
    location: "Fridge",
    countAsUnits: false,
    batches: [{ id: 6, qty: 1, fillLevel: "almost_empty", sealed: false, bestBefore: "2026-04-10" }],
  },
  {
    id: "6",
    name: "Frozen Peas",
    type: "ingredient",
    location: "Freezer",
    countAsUnits: false,
    batches: [{ id: 7, qty: 1, fillLevel: "half", sealed: false, bestBefore: "2026-09-01" }],
  },
  {
    id: "7",
    name: "Cumin",
    type: "ingredient",
    location: "Spice Rack",
    countAsUnits: false,
    batches: [{ id: 8, qty: 1, fillLevel: "just_opened", sealed: false, bestBefore: "2027-01-01" }],
  },
  {
    id: "8",
    name: "Paprika",
    type: "ingredient",
    location: "Spice Rack",
    countAsUnits: false,
    batches: [{ id: 9, qty: 1, fillLevel: "almost_empty", sealed: false, bestBefore: "2026-12-01" }],
  },
  {
    id: "9",
    name: "Basmati Rice",
    type: "ingredient",
    location: "Pantry",
    countAsUnits: false,
    batches: [{ id: 10, qty: 1, fillLevel: "half", sealed: false, bestBefore: "2027-03-01" }],
  },
  {
    id: "10",
    name: "Stew",
    type: "cooked_meal",
    location: "Freezer",
    countAsUnits: false,
    batches: [
      {
        id: 11,
        qty: 1,
        fillLevel: "just_opened",
        sealed: false,
        bestBefore: "2026-05-01",
        dateMade: "2026-03-25",
      },
      {
        id: 12,
        qty: 1,
        fillLevel: "just_opened",
        sealed: false,
        bestBefore: "2026-05-01",
        dateMade: "2026-03-25",
      },
    ],
  },
  {
    id: "11",
    name: "Olive Oil",
    type: "ingredient",
    location: "Pantry",
    countAsUnits: false,
    batches: [
      {
        id: 13,
        qty: 1,
        fillLevel: "almost_empty",
        sealed: false,
        bestBefore: "2026-08-01",
        finished: true,
      },
    ],
  },
];
